In [268]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [269]:
import numpy as np
import pandas as pd
s1=pd.Series([23,24,25,12,'32'])
s1

0    23
1    24
2    25
3    12
4    32
dtype: object

In [270]:
s2=pd.Series([23,24,25,12,32])
s2

0    23
1    24
2    25
3    12
4    32
dtype: int64

In [271]:
s3=pd.Series([23,24,25,12,32.5])
s3

0    23.0
1    24.0
2    25.0
3    12.0
4    32.5
dtype: float64

In [272]:
s2=pd.Series([23,24,25,12,32],index=['a','b','c','d','e'])
s2

a    23
b    24
c    25
d    12
e    32
dtype: int64

In [273]:
s3=pd.Series([23,24,25,12,32],index=['a','b','c','d','e'],dtype='float')
s3

a    23.0
b    24.0
c    25.0
d    12.0
e    32.0
dtype: float64

In [274]:
s4=pd.Series({'e':65,'f':43,'c':45})
s4

e    65
f    43
c    45
dtype: int64

In [275]:
d1=pd.DataFrame([43,54,65,76])
d1

    0
0  43
1  54
2  65
3  76

In [276]:
d2=pd.DataFrame(s2)
d2

    0
a  23
b  24
c  25
d  12
e  32

In [277]:
d3=pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns=['a','b','c'])
d3

   a  b  c
0  2  3  4
1  4  5  6
2  1  2  3

In [278]:
d3=pd.DataFrame([[2,3,4],[4,5,6],[1,2,3]],columns=['a','b','c'],index=['x','y','z'])
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [279]:
dic=[{'alex':1,'joe':2},{'ema':5,'dora':10,'alice':20},{'ema':5,'dora':10,'alice':20}]
pd.DataFrame(dic,index=['a','b','c'])

   alex  joe  ema  dora  alice
a   1.0  2.0  NaN   NaN    NaN
b   NaN  NaN  5.0  10.0   20.0
c   NaN  NaN  5.0  10.0   20.0

In [280]:
d3

   a  b  c
x  2  3  4
y  4  5  6
z  1  2  3

In [281]:
print(d3['a'])
print(d3['c'])

x    2
y    4
z    1
Name: a, dtype: int64
x    4
y    6
z    3
Name: c, dtype: int64

In [282]:
d3['d']=d3['a']*d3['b']
d3['e']=d3['a']+d3['d']
d3

   a  b  c   d   e
x  2  3  4   6   8
y  4  5  6  20  24
z  1  2  3   2   3

In [283]:
pop = d3.pop('b')
d3

   a  c   d   e
x  2  4   6   8
y  4  6  20  24
z  1  3   2   3

In [284]:
del d3['d']
d3

   a  c   e
x  2  4   8
y  4  6  24
z  1  3   3

In [285]:
d3.pop('a')
d3

   c   e
x  4   8
y  6  24
z  3   3

In [286]:
d3.insert(1,'new1',d3['c'])
d3

   c  new1   e
x  4     4   8
y  6     6  24
z  3     3   3

In [287]:
d={'c':1,'new1':33,'e':22}
df11=d3._append(d,ignore_index=True)
df11

   c  new1   e
0  4     4   8
1  6     6  24
2  3     3   3
3  1    33  22

In [288]:
d4=pd.DataFrame({'abc':np.random.randint(2,6,size=(7)),'bcd':np.random.randint(4,10,size=(7)),'cde':np.random.randint(3,10,size=(7))})
d4

   abc  bcd  cde
0    2    9    5
1    3    7    9
2    5    9    3
3    5    6    6
4    5    5    3
5    3    4    5
6    2    9    9

In [289]:
d4.head()

   abc  bcd  cde
0    2    9    5
1    3    7    9
2    5    9    3
3    5    6    6
4    5    5    3

In [290]:
d4.tail()

   abc  bcd  cde
2    5    9    3
3    5    6    6
4    5    5    3
5    3    4    5
6    2    9    9

In [291]:
d4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   abc     7 non-null      int64
 1   bcd     7 non-null      int64
 2   cde     7 non-null      int64
dtypes: int64(3)
memory usage: 300.0 bytes

In [292]:
d4.describe()

            abc       bcd       cde
count  7.000000  7.000000  7.000000
mean   3.571429  7.000000  5.714286
std    1.397276  2.081666  2.497618
min    2.000000  4.000000  3.000000
25%    2.500000  5.500000  4.000000
50%    3.000000  7.000000  5.000000
75%    5.000000  9.000000  7.500000
max    5.000000  9.000000  9.000000

In [293]:
print(d4)
print(d4.loc[1,'cde'])
print(d4.loc[1,'bcd'])

   abc  bcd  cde
0    2    9    5
1    3    7    9
2    5    9    3
3    5    6    6
4    5    5    3
5    3    4    5
6    2    9    9
9
7

In [294]:
d4.loc[2:5,['abc','cde']]

   abc  cde
2    5    3
3    5    6
4    5    3
5    3    5

In [295]:
d4.loc[[3,5,6],['abc','cde']]

   abc  cde
3    5    6
5    3    5
6    2    9

In [296]:
print(d4.iloc[3,0])

5

In [297]:
d4.iloc[2:7,[0,2]]

   abc  cde
2    5    3
3    5    6
4    5    3
5    3    5
6    2    9

In [298]:
d4.iloc[[1,3,5],[0,1]]

   abc  bcd
1    3    7
3    5    6
5    3    4

In [299]:
d4.abc

0    2
1    3
2    5
3    5
4    5
5    3
6    2
Name: abc, dtype: int64

In [300]:
d4.abc.values

array([2, 3, 5, 5, 5, 3, 2])

In [301]:
d4['sub']=d4.abc.values-d4.cde.values-d4.bcd.values
d4

   abc  bcd  cde  sub
0    2    9    5  -12
1    3    7    9  -13
2    5    9    3   -7
3    5    6    6   -7
4    5    5    3   -3
5    3    4    5   -6
6    2    9    9  -16

In [302]:
a=[['rk',102,15000],['rama',103,20000],['krishna',104,25000]]
df1=pd.DataFrame(a,columns=['name','id','salary'])
df1

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000

In [303]:
y=df1[df1.salary>=20000]
print(y)
y[['id','salary']]

      name   id  salary
1     rama  103   20000
2  krishna  104   25000

    id  salary
1  103   20000
2  104   25000

In [304]:
df1=df1._append({'name':'aravind','id':105,'salary':30000},ignore_index=True)
df1

      name   id  salary
0       rk  102   15000
1     rama  103   20000
2  krishna  104   25000
3  aravind  105   30000

In [305]:
df1=df1._append({'name':np.nan,'id':105,'salary':30000},ignore_index=True)
df1

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3  aravind  105.0  30000.0
4      NaN  105.0  30000.0

In [306]:
d4

   abc  bcd  cde  sub
0    2    9    5  -12
1    3    7    9  -13
2    5    9    3   -7
3    5    6    6   -7
4    5    5    3   -3
5    3    4    5   -6
6    2    9    9  -16

In [307]:
df1.isnull()

    name     id  salary
0  False  False   False
1  False  False   False
2  False  False   False
3  False  False   False
4   True  False   False

In [308]:
print(df1.isnull().sum())

name      1
id        0
salary    0
dtype: int64

In [309]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   id      5 non-null      float64
 2   salary  5 non-null      float64
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes

In [310]:
df1.dropna()

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3  aravind  105.0  30000.0

In [311]:
df1

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3  aravind  105.0  30000.0
4      NaN  105.0  30000.0

In [312]:
df1.fillna(value='abc')

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3  aravind  105.0  30000.0
4      abc  105.0  30000.0

In [313]:
df1

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
2  krishna  104.0  25000.0
3  aravind  105.0  30000.0
4      NaN  105.0  30000.0

In [314]:
df1.drop([2],axis=0,inplace=True)
df1

      name     id   salary
0       rk  102.0  15000.0
1     rama  103.0  20000.0
3  aravind  105.0  30000.0
4      NaN  105.0  30000.0

In [315]:
df=pd.DataFrame({'Animal':['Falcon','Falcon','Parrot','Parrot'],'Max Speed':[380.,370.,24.,26.],'Wind Speed':[380.,370.,24.,26.]})
df

   Animal  Max Speed  Wind Speed
0  Falcon      380.0       380.0
1  Falcon      370.0       370.0
2  Parrot       24.0        24.0
3  Parrot       26.0        26.0

In [316]:
df.groupby(['Animal']).mean()

        Max Speed  Wind Speed
Animal
Falcon      375.0       375.0
Parrot       25.0        25.0

In [317]:
df.T

                 0       1       2       3
Animal      Falcon  Falcon  Parrot  Parrot
Max Speed    380.0   370.0    24.0    26.0
Wind Speed   380.0   370.0    24.0    26.0

In [318]:
data={'first name':['Arun','jebu','venkat','rekha','majid','mohsin'],'last name':['kumar','jacob','raghavan','singh','khan','khan'],'employmenttype':['service','business','student','service','business','business'],'country':['india','usa','usa','sweden','australia','germany']}
df=pd.DataFrame(data,columns=['first name','last name','employmenttype','country'])
print(df)

  first name last name employmenttype    country
0       Arun     kumar        service      india
1       jebu     jacob       business        usa
2     venkat  raghavan        student        usa
3      rekha     singh        service     sweden
4      majid      khan       business  australia
5     mohsin      khan       business    germany

In [319]:
df1=pd.get_dummies(df['employmenttype'],dtype='int')
df2=pd.get_dummies(df['country'],dtype='int')
print(df1)
print(df2)

   business  service  student
0         0        1        0
1         1        0        0
2         0        0        1
3         0        1        0
4         1        0        0
5         1        0        0
   australia  germany  india  sweden  usa
0          0        0      1       0    0
1          0        0      0       0    1
2          0        0      0       0    1
3          0        0      0       1    0
4          1        0      0       0    0
5          0        1      0       0    0

In [320]:
india_weather=pd.DataFrame({'city':["mumbai","delhi","banglore"],
                            'temperature':[32,45,30],
                            'humidity':[80,60,78]})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78

In [321]:
us_weather=pd.DataFrame({'city':["new york","chicago","orlando"],
                            'temperature':[21,14,35],
                            'humidity':[68,65,75]})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [323]:
df=pd.concat([india_weather,us_weather])
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [324]:
df=pd.concat([india_weather,us_weather],ignore_index=True)
df

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  banglore           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

In [325]:
emp={"name":["parker","smith","william","parker"],
     "age":[21,32,29,21]}
info=pd.DataFrame(emp)
print(info)
print("__________________")
info=info.drop_duplicates()
print(info)

      name  age
0   parker   21
1    smith   32
2  william   29
3   parker   21
__________________
      name  age
0   parker   21
1    smith   32
2  william   29

In [326]:
def calc_sum(kiran):
  return kiran+1
data={'x':[50,40,30],
      'y':[300,1112,42]}
df=pd.DataFrame(data)
print(df)
x=df.apply(calc_sum)
print(x)

    x     y
0  50   300
1  40  1112
2  30    42
    x     y
0  51   301
1  41  1113
2  31    43

In [328]:
data={'first name':['Arun','jebu','venkat','rekha','majid','mohsin'],'last name':['kumar','jacob','raghavan','singh','khan','khan'],'employmenttype':['service','business','student','service','business','business'],'country':['india','usa','usa','sweden','australia','germany']}
df=pd.DataFrame(data,columns=['first name','last name','employmenttype','country'])
d=pd.Categorical(df['country'])
print(d)

['india', 'usa', 'usa', 'sweden', 'australia', 'germany']
Categories (5, object): ['australia', 'germany', 'india', 'sweden', 'usa']